### PR TITLE
Huge API overhaul and migration to RxJava2.

### LINKED ISSUE #28: Android + Kotlin build error: Multiple dex files define Lorg/jetbrains/annotations/NotNull
If you create new Android project, configure Kotlin (add Kotlin dependencies) and add RxStore dependencies Android build will fail with Error:
_Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lorg/jetbrains/annotations/NotNull;_

(make sure to run gradle _build_ task becouse with incremental compilation this may actually work sometimes )

This happens becouse both Kotlin and RxStore are adding the same dependency to the project _org.jetbrains.annotations_

Fix
`
compile ('au.com.gridstone.rxstore:rxstore:5.0.5') { exclude group: 'org.jetbrains'}
compile ('au.com.gridstone.rxstore:rxstore-kotlin:5.0.5') { exclude group: 'org.jetbrains'}
compile ('au.com.gridstone.rxstore:converter-moshi:5.0.5') { exclude group: 'org.jetbrains'}
`

For now this fix works, but I wondes can we make it work by default? (kind of making dependencies optional?)

### PR DESCRIPTION
**Pull request by chris-horner**
Here's my take on Rxjava2 support for RxStore. I've changed quite a bit, so let's unpack things...

I've completely killed `StoreProvider`. This is because:
- Having `ValueStore` and `ListStore` as inner classes just made calling code ugly.
- Enforcing a `Scheduler` for all store interactions sucked.
- Creating stores manually really isn't that hard. Reusing converter instances and making files in directories is something that consuming applications can manage on their own, and this gives them greater flexibility.

`ListStores` and `ValueStores` are now created by calling a constructor or by using the provided factory methods in `rxstore-kotlin`. I feel this is *much* simpler for people to understand and make use of.

I removed the `.delete()` method on both stores and now calling `clear()` actually deletes the file on disk. I'm not quite sure why I ever made the distinction between the two, and rendering a store inoperable after calling `.delete()` seemed a bit odd. This helps simplify things.

All `observeXXX()` calls now return an appropriate RxJava2 structure that operates on no particular `Scheduler`. The read/write locks are sufficient for preventing collisions and now calling applications have more options for schedulers.

All methods such as `put()`, `add()`, `remove()` etc now come in two flavours: one that takes a `Scheduler` and one that does not. The variant that doesn't take a `Scheduler` as an argument is just an alias that calls through to the other using `Schedulers.io()`. This allows for code such as
```java
listStore.add(new Item());
```
when callers just want something added and written to disk asynchronously using a sensible `Scheduler`.

I also took this opportunity to port almost all of our tests to Kotlin as I feel it makes them much easier to read! (I couldn't do it for `JacksonConverter` however because Jackson is a special snowflake...)

I've also removed the dependency on Jetbrains' `@NotNull` annotation lib and replaced it with RxJava2's inbuilt `@NonNull` and `@Nullable` annotations. I don't believe the IntelliJ Kotlin plugin understands these annotations by default, but I'll get a PR up on that soon as I feel a few people are going to want it. At least this fixes #28.

-------------------------------------------------

I haven't added any documentation to the new classes yet as I feel things may change now that this is up for discussion. If we do think this big API change is the appropriate way to go then I'll go ahead and add documentation in a separate PR.

What do you think, @Altoyyr?

### CODE REVIEW

File: rxstore/src/main/java/au/com/gridstone/rxstore/ListStore.java [hunk 1]
```diff
@@ -0,0 +1,412 @@
...
+    addOrReplace(value, Schedulers.io(), predicateFunc);
+  }
+
+  public void addOrReplace(@NonNull T value, @NonNull Scheduler scheduler,
+      @NonNull ReplacePredicateFunc<T> predicateFunc) {
+    assertNotNull(scheduler, "scheduler");
+    observeAddOrReplace(value, predicateFunc).subscribeOn(scheduler).subscribe();
+  }
+
+  public interface RemovePredicateFunc<T> {
```
Comment (huan-nguyen) [inline rxstore/src/main/java/au/com/gridstone/rxstore/ListStore.java]: Perhaps we can take this chance to merge `RemovePredicateFunc` and `ReplacePredicateFunc` since they are basically the same thing?

Comment (chris-horner) [inline rxstore/src/main/java/au/com/gridstone/rxstore/ListStore.java]: Good call! Fixed.

**Comment by chris-horner** [comment]
Updated, thanks @stphven

**Comment by Altoyyr** [comment]
I think it looks good for a first iteration.

**Comment by Altoyyr** [comment]
I think it looks good in general for a first iteration. 

Points I think would make sense:

- Extract Interfaces for the stores and create them via a static factory
This would help with "unused" warnings in IntelliJ and provide the possibility to mock the store for client tests
- Only emit `StoreException` when something goes wrong
Knowing which exception will be thrown from stores will help clients write cleaner code

Otherwise if looks really decent to me.

**Comment by chris-horner** [comment]
I'm not sure defining interfaces for the two stores is the best way to go. They're pretty darn simple and it's quite easy to use their concrete implementations in unit tests. In general I think it's a good idea to [not overuse mocks](https://testing.googleblog.com/2013/05/testing-on-toilet-dont-overuse-mocks.html).

Other libraries that provide similar functionality have seen [fairly heated debates](https://github.com/f2prateek/rx-preferences/issues/31) on similar topics, and so fair I haven't seen anything that convinces me that making unused interfaces is a good idea. Happy to engage in a discussion on this however if you firmly believe it's a good idea!

On the topic of exceptions; I'm not sure we see much benefit there either. Given that most interactions with this library are done through Rx chains, exceptions are going to be delivered through `onError()` callbacks. Right now I can't think of a time I'd ever care about the specific exception type delivered in `onError()` when interacting with a store, but again I'm happy to be convinced otherwise.

Let me know what you think :)

**Comment by Altoyyr** [comment]
I think throwing always the same type of exception helps for a clean interface, but I have no strong feelings about this. 

About the other point for the interfaces, I strongly agree with dalewking (user pushing for interface from the linked issue). An Interface is nothing that is complicated to create and helps the clients a lot with testing. When I test my classes I prefer to absolutely mock/fake every dependency to really get the unit under test in isolation. 

With the current approach the client has to create a wrapper around the store, which is quite ugly and cumbersome. I strongly thing providing an interface is a good thing.

**Comment by chris-horner** [comment]
Thinking more on exceptions, I think throwing different types potentially helps callers quickly track down what the problem actually is. I'm not sure we need to wrap `IOException` in another type. (Maybe this stems from me using nothing but Kotlin lately where I feel like dealing with exceptions is easier!)

On interfaces for mocks, my main concern is there's nuance to the behaviour of a store. Take the `observe()` method for example. The `Observable` it emits returns the current value as soon as someone subscribes to it before delivering subsequent updates. Anyone who mocks a store interface will need to replicate that same behaviour. The unit test you write using a mock is only useful if the mock behaves exactly like the real implementation.

That being said I recognise that even if I don't think it's useful, many people will. The cost to me of making it an interface is small and it greatly helps those who wish to mock, so perhaps it's the best course of action. I'll think about it some more over the weekend, but I'm currently leaning towards doing it to make the pro-mockers happy 😄

**Comment by chris-horner** [comment]
PR updated! Now with interfaces and static factory functions. Let me know what you think, @Altoyyr 😄

File: rxstore/src/main/java/au/com/gridstone/rxstore/RealValueStore.java [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+import java.io.File;
+import java.io.IOException;
+import java.lang.reflect.Type;
+import java.util.concurrent.locks.ReentrantReadWriteLock;
+
+import static au.com.gridstone.rxstore.Locks.runInReadLock;
+import static au.com.gridstone.rxstore.Locks.runInWriteLock;
+import static au.com.gridstone.rxstore.Preconditions.assertNotNull;
+
+final class RealValueStore<T> implements ValueStore<T> {
```
Comment (Altoyyr) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RealValueStore.java]: I would name this class ValueStoreImpl, so the interface and implementation class are close to each other in the 
package when alphabetically sorted.

File: rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+ * limitations under the License.
+ */
+
+package au.com.gridstone.rxstore;
+
+import io.reactivex.annotations.NonNull;
+import java.io.File;
+import java.lang.reflect.Type;
+
+public class RxStore {
```
Comment (Altoyyr) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: I would name this one RxStoreFactory and make it abstract to follow the Abstract-Factory-Pattern conventions

File: rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+  private RxStore() {
+    throw new AssertionError("No instances.");
+  }
+
+  public static <T> ValueStore<T> value(@NonNull File file, @NonNull Converter converter, @NonNull
```
Comment (Altoyyr) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: I would rename this one to createValueStore

File: rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+      Type type) {
+    return new RealValueStore<T>(file, converter, type);
+  }
+
+  public static <T> ListStore<T> list(@NonNull File file, @NonNull Converter converter,
```
Comment (Altoyyr) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: and this one to createListStore.

I think this would add extra readability

File: rxstore/src/main/java/au/com/gridstone/rxstore/RealListStore.java [hunk 6]
```diff
@@ -0,0 +1,402 @@
...
+import java.util.ArrayList;
+import java.util.Collections;
+import java.util.List;
+import java.util.concurrent.locks.ReentrantReadWriteLock;
+
+import static au.com.gridstone.rxstore.Locks.runInReadLock;
+import static au.com.gridstone.rxstore.Locks.runInWriteLock;
+import static au.com.gridstone.rxstore.Preconditions.assertNotNull;
+
+final class RealListStore<T> implements ListStore<T> {
```
Comment (Altoyyr) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RealListStore.java]: I would name this class ListStoreImpl, so the interface and implementation class are close to each other in the 
package when alphabetically sorted.

File: rxstore/src/main/java/au/com/gridstone/rxstore/RealValueStore.java (hunk 2 above)
Comment (chris-horner) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RealValueStore.java]: `Impl` is something that rubs me the wrong way on a fundamental level. Interfaces define protocols and classes define implementations. My personal opinion is that `Impl` is a naming anti-pattern, and I do my best to avoid it at all costs. It's nothing but noise. Not something I think I will ever budge on, sorry!

File: rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java (hunk 3 above)
Comment (chris-horner) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: Again, just opinion but I really dislike `Factory` as a suffix. I know it's a pattern that many developers use, but I cannot stand it. After working with codebases that Square develop I've grown very fond of terse names and methods. (I take a lot of inspiration from the likes of Okio).

File: rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java (hunk 4 above)
Comment (chris-horner) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: I initially had this as `createValue()` and decided to cut it down even further! @stphven, @jsprincep, @huan-nguyen, any thoughts on naming here?

Comment (stphven) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: Actually, I'm a bit partial to `RxStore.valueStore()`. Though I can see why you'd want to avoid the duplicate `store`.

Comment (jsprincep) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: I'd actually go with `RxStore.valueStore()`. Despite the fact that you're repeating `store`, I feel like `RxStore.value()` is too ambiguous, and the `create` is unnecessary.

Comment (huan-nguyen) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: I'd go with `RxStore.valueStore` as well since I think we need the word `store` here to make it clear that we're creating a `store`.

Comment (Altoyyr) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: I disagree. I think there is no point in saving a few characters if you loose understandability. 
`RxStore` does not tell me that this creates something. 
`.valueStore` or `.value()` does neither. It looks like a weird getter to me. 
I strongly believe that a method should be named to express what it does. 

Naming the factory `Factory` and the method `create...` or `something` is way more expressive for the cost of a few more characters (which are free). This also overlaps with what is written in the book "Agile Software Development" by Robert C. Martin.

In the end, I can't make you change it and we might not agree. But if you look at it like someone who starts using your library with no previous knowledge it is clear, that `RxStoreFactory.createValueStore()` expresses way better what the class/method does than `RxStore.value()`

File: rxstore/src/main/java/au/com/gridstone/rxstore/RealValueStore.java (hunk 2 above)
Comment (Altoyyr) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RealValueStore.java]: You say _classes define implementations_ but you don't wanna name it `...Impl` does sound a bit weird to me. `Real...` in the end is also noise but it moves the class in the project away from it's interface.  
Keeping things that belong together close is - for me - a good concept. 
But I do not feel as strongly about this as about the factory comment.  :)

Comment (chris-horner) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RealValueStore.java]: I'm not a fan of `Real` either, but I think it more accurately portrays how there is only one implementation of the interface. It's the only _real_ implementation, and everything else will be a mock. `Impl` seems tautological to me. All classes are implementations, so why include the word if that's already what it is?

Personal opinion again, but I feel that any time words like `Real` or `Impl` are needed it's a huge code smell of over abstraction.

File: rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java (hunk 4 above)
Comment (chris-horner) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: With the current set of refactoring, the only way to begin interfacing with this library is through the two static methods defined on `RxStore`. With that in mind I strongly believe that including `Factory` in the name is unnecessary and ugly.

Let's look at Okio for example. The main ways you interface with that particular library are `Okio.buffer()`, `Okio.source()`, and `Okio.sink()`. I think this is particularly elegant and I certainly wouldn't want these to be called `OkioFactory.createBuffer()`. I simply haven't missed that naming convention; only enjoyed its absence.

Given that we're generating reactive stores, I don't think it's difficult for a developer to intuit what the results of `RxStore.value()` and `RxStore.list()` will do. (Especially when we're in a statically typed language and we can see explicitly what the return type is). I'll think on it and look through more APIs that I've enjoyed working with, but I'm not sure I'm convinced at the moment.

Comment (Altoyyr) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: Yeah, I think we will not come to a mutual agreement on this topic. 
Which is absolutely fine of course. 

Anyway I am happy with the changes and the update to RxJava2 and would love to see a release soon :)

Comment (chris-horner) [inline rxstore/src/main/java/au/com/gridstone/rxstore/RxStore.java]: Mmm, I guess it's just one of those fundamental differences of opinion. I would like to say thanks for engaging in a good discussion though! It's always nice when people participate in polite debate and I really appreciate it. I'll merge this PR now and write some documentation tomorrow morning. Hopefully PR #38 can be updated too and we get that included for the RxJava2 compatible release! 😄
